#Pulling base image from Docker hub repository.
FROM centos:centos6

#Author
MAINTAINER Mahesh Singh, mahesh.3246@gmail.com

# Install dependencies
RUN yum -y update && yum -y install wget && yum -y install tar

# Prepare environment 
ENV JAVA_HOME /opt/java
ENV CATALINA_HOME /opt/tomcat 
ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/bin:$CATALINA_HOME/scripts

# Install Oracle Java7
ENV JAVA_VERSION 7u112
ENV JAVA_BUILD 7u112-b15

RUN wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/${JAVA_BUILD}/jdk-${JAVA_VERSION}-linux-x64.tar.gz && tar -xvf jdk-${JAVA_VERSION}-linux-x64.tar.gz && rm jdk*.tar.gz && mv jdk* ${JAVA_HOME}

# Install Tomcat
ENV TOMCAT_MAJOR 7
ENV TOMCAT_VERSION 7.0.59

RUN wget http://ftp.riken.jp/net/apache/tomcat/tomcat-${TOMCAT_MAJOR}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz && tar -xvf apache-tomcat-${TOMCAT_VERSION}.tar.gz && rm apache-tomcat*.tar.gz && mv apache-tomcat* ${CATALINA_HOME}

RUN chmod +x ${CATALINA_HOME}/bin/*sh

# Create Tomcat admin user
ADD create_admin_user.sh $CATALINA_HOME/scripts/create_admin_user.sh
ADD tomcat.sh $CATALINA_HOME/scripts/tomcat.sh
RUN chmod +x $CATALINA_HOME/scripts/*.sh

# Create tomcat user
RUN groupadd -r tomcat && \
 useradd -g tomcat -d ${CATALINA_HOME} -s /sbin/nologin  -c "Tomcat user" tomcat && chown -R tomcat:tomcat ${CATALINA_HOME}

WORKDIR /opt/tomcat

USER tomcat
CMD ["tomcat.sh"]